{% set version = '0.2.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-quickmatch
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/quickmatch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quickmatch/quickmatch_{{ version }}.tar.gz
  sha256: 218ba3570741e46d8fcb98ed5958ddca4465fe7db1c7cf7f3fbebb3f4a4866e4

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-distances
    - r-sandwich
    - r-scclust >=0.2.0
  run:
    - r-base
    - r-distances
    - r-sandwich
    - r-scclust >=0.2.0

test:
  commands:
    - $R -e "library('quickmatch')"           # [not win]
    - "\"%R%\" -e \"library('quickmatch')\""  # [win]

about:
  home: https://github.com/fsavje/quickmatch
  license: GPL-3.0-or-later
  summary: Provides functions for constructing near-optimal generalized full matching. Generalized
    full matching is an extension of the original full matching method to situations
    with more intricate study designs. The package is made with large data sets in mind
    and derives matches more than an order of magnitude quicker than other methods.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: quickmatch
# Type: Package
# Title: Quick Generalized Full Matching
# Version: 0.2.3
# Date: 2024-07-31
# Authors@R: c( person("Fredrik", "Savje", email = "rpackages@fredriksavje.com", role = c("aut", "cre")), person("Jasjeet", "Sekhon", role = "aut"), person("Michael", "Higgins", role = "aut"))
# Description: Provides functions for constructing near-optimal generalized full matching. Generalized full matching is an extension of the original full matching method to situations with more intricate study designs. The package is made with large data sets in mind and derives matches more than an order of magnitude quicker than other methods.
# Depends: R (>= 3.4.0), distances
# Imports: sandwich, scclust (>= 0.2.0), stats
# Suggests: testthat
# NeedsCompilation: yes
# License: GPL (>= 3)
# URL: https://github.com/fsavje/quickmatch
# BugReports: https://github.com/fsavje/quickmatch/issues
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Packaged: 2024-07-31 15:56:04 UTC; fredriksavje
# Author: Fredrik Savje [aut, cre], Jasjeet Sekhon [aut], Michael Higgins [aut]
# Maintainer: Fredrik Savje <rpackages@fredriksavje.com>
# Repository: CRAN
# Date/Publication: 2024-07-31 22:30:18 UTC
